name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

#    - name: Set up Python
#      uses: actions/setup-python@v5
#      with:
#        python-version: '3.11'
#
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest  # Или другой фреймворк

#  deploy:
#    needs: build-and-test
#    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy script
      run: echo "Deploying to production..."
